### PR TITLE
Restler upgrade

### PR DESCRIPTION
**Pull request by bleonard**
[Restler](https://github.com/danwrong/restler) has not been updated in quite some time and there is a security issue in `qs` as noted in https://github.com/MadKudu/node-marketo/issues/66.

To simplify things, I decided to vendor the two `restler` files and use them directly, giving `node-marketo` a chance to handle deprecations and security issues itself.

I fixed the deprecation I saw regarding the use of `new Buffer()`.

The tests are somewhat challenging to run because they expect specific list names and lead ids, but I tested it with the ones I could.

### CODE REVIEW

**Comment by bleonard** [comment]
We've been using this for a while. Any interest in merging? @pcothenet

**Comment by GhassenRjab** [comment]
Nice work @bleonard 👍 

I think we should use another library instead of restler instead though.

This will prevent us from doing additional maintenance work in the library.

What do you think?

**Comment by bleonard** [comment]
That's probably the right idea, but we aren't using this any more. So I'll leave it up to others. Best of luck!

**Comment by mdarcemont** [comment]
restler has been replaced by axios. Closing. 
Thank you for your work @bleonard

**Pull request closed without merging**
