### PR TITLE
Added Folder section

### PR DESCRIPTION
**Pull request by andrewzolotukhin**

### CODE REVIEW

**Comment by andrewzolotukhin** [comment]
hi @GhassenRjab, could you please consider to merge this?

**Review by GhassenRjab — APPROVED** [review]

**Comment by GhassenRjab** [comment]
@andrewzolotukhin this has been merged! It will be released in the next publish

**Comment by andrewzolotukhin** [comment]
Thanks!

**Comment by GhassenRjab** [comment]
Release with 0.11.0

**Pull request merged**
