### PR TITLE
Added bulkactivity/lead extract

### PR DESCRIPTION
**Pull request by Grimace1975**
Added Bulk Extracts

### CODE REVIEW

**Comment by pcothenet** [comment]
Awesome! I can probably review and publish tomorrow.

Would you mind adding a few words to the doc on how to use?

**Comment by Grimace1975** [comment]
Sure, I will add some to the docs, also missing a test.

I am in the process of converting over to .net, so will submit that as well later.

**Comment by Grimace1975** [comment]
Updated, has issues trying to replay my tests with your default token.

**Comment by pcothenet** [comment]
Awesome. Yeah, the replay tests are super finicky (I was struggling with them yesterday)

**Comment by pcothenet** [comment]
Published as 0.4.1. 

Since it's a new feature, proposing to overlook the test errors for now, but confirming they fail on my end.

**Comment by Grimace1975** [comment]
Also needed to upgrade Replay was having errors on my end. And the StatusTillCompeted method pulls the status ever 60seconds, this will not be able to use replay. So I have a condition on those parts of the test.

Glad I could help,

Now working on the C# port my team needs lol.

Will let you evaluate that too. Under /src.net/

**Pull request merged**
