### PR TITLE
Add event emitter to log apiCalls

### PR DESCRIPTION
**Pull request by pcothenet**
Experimental feature to allow for better surveillance of the total number of API calls made.

The connection keeps track of the number of Marketo API call it makes. Each one gets emitted as an 'apiCall' event by the client.

Usable via
```
marketo.on('apiCall', data => {
    console.log(data);
});
```

### CODE REVIEW

**Comment by conortm** [comment]
@pcothenet Hello! First of all, thanks for you and your team's great work!

It looks like this PR introduces ES6 syntax (arrow functions) which isn't supported by node v0.10.x. I think you'll need to bump up the version of node required in your `package.json`, or look into some other solution.

Thanks again!

**Comment by pcothenet** [comment]
Ah good call. I should be able to use regular function, that will keep backward compatibility a bit longer.

Thanks!

**Comment by conortm** [comment]
@pcothenet Word! Thanks!

**Comment by pcothenet** [comment]
#35 done!

**Comment by pcothenet** [comment]
Actually, introduced another bug :|. Fixing now.

**Pull request merged**
