### PR TITLE
fixing the issue when the query returns no results (leads) for lists

### PR DESCRIPTION
**Pull request by Alevsk**
The stream was not starting/ending (i think it was discussed originally here: [https://github.com/MadKudu/node-marketo/issues/26](https://github.com/MadKudu/node-marketo/issues/26))

### CODE REVIEW

**Comment by pcothenet** [comment]
Can you make it `if (data.result && data.result.length > 0)` to avoid failing if result is not defined?

**Comment by Alevsk** [comment]
Hi pcothenet, I just pushed the fix.
best regards.

**Comment by pcothenet** [comment]
Thanks!

Also, do you think it should emit an error when empty?
Seems like that could happen in normal scenarios. Seems a bit strong to fail the stream, no?

**Comment by Alevsk** [comment]
Hi, I removed the error emit.
best regards.

**Comment by pcothenet** [comment]
Merged and published as 0.3.6

**Pull request merged**
